# Generated by Django 2.0.2 on 2018-03-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='img_url',
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(default='location_images/default.png', upload_to='location_images'),
        ),
    ]
