# Generated by Django 2.0.2 on 2018-03-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180303_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='predators',
            new_name='Best_Time_to_Visit',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='num_restaurants',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='location_images'),
        ),
    ]
