# Generated by Django 2.0.2 on 2018-03-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180308_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
